version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  my_app:
    image: cei-exam-test
    environment:
      - DATABASE_TYPE=redis
      - REDIS_HOST=redis
    ports:
      - 80:80
    depends_on:
      - redis
