podTemplate(
    serviceAccount: "jenkins",
    imagePullSecrets: ['docker-registry'],
    containers: [
        containerTemplate(name: 'podman', 
            image: '885903886121.dkr.ecr.eu-south-2.amazonaws.com/jenkins-agent', 
            alwaysPullImage: true, 
            privileged: true ,
            command: 'sleep', 
            args: '99d'
            volumes: [
                secretVolume(mountPath: "/tmp/dr", secretName: 'docker-registry'),
            ]
            )
    ]) {

      node(POD_LABEL) {
        container('podman'){  
          env.IMAGE_NAME='exam-server'
          env.IMAGE_REPO='885903886121.dkr.ecr.eu-south-2.amazonaws.com'
          stage ('Checkout'){
            git url: 'https://github.com/bbardelli/cei-aws.git', branch: 'main'
          }
          stage('Build docker image') {
            sh 'podman build -t $IMAGE_REPO/$IMAGE_NAME:$BUILD_NUMBER -t $IMAGE_REPO/$IMAGE_NAME:latest ./exam-server/'
          }
          stage('Push docker image') {
            withCredentials([usernameColonPassword(credentialsId: 'registry', variable: 'USERPASS')]){
              sh 'podman push $IMAGE_REPO/$IMAGE_NAME:$BUILD_NUMBER --authfile=/tmp/dr/.dockerconfigjson'
              sh 'podman push $IMAGE_REPO/$IMAGE_NAME:latest --authfile=/tmp/dr/.dockerconfigjson'
            }
          }
        }
      }
}