apiVersion: v1
kind: Service
metadata:
  name: canary
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30680
  selector:
    app: exam-test
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: "redis-exam"
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP