apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 45.1.0
    chart: kube-prometheus-stack
    helm:
      valuesObject:
        grafana:
          enabled: true
          adminUser: admin
          adminPassword: admin
          service:
            type: NodePort
            nodePort: 30280
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    